# Generated by Django 6.1.1 on 2026-09-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_date_of_birth_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Selecione uma opção'), ('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outro', 'Outro'), ('Prefiro não informar', 'Prefiro não informar')], max_length=20),
        ),
    ]
