# Generated by Django 6.1.1 on 2026-09-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_verified_teacher',
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Selecione uma opção'), ('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outro', 'Outro'), ('-', 'Prefiro não informar')], max_length=20),
        ),
    ]
